### ISSUE TITLE
SSH Keys have incorrect permissions on Windows, preventing things like pulling files

### ISSUE THREAD

**Issue by Soundvessel** [kalabox/kalabox#1338]
**Tell us about your setup**

Kalabox Beta 1, perviously Alpha 3 and 4 but those were fully uninstalled.

Windows 10 Pro, recent standard clean install.

**Tell us about your bug**

1. Setup new D8 site on Pantheon [following their instructions](https://pantheon.io/docs/drupal-8/) keeping SFTP mode on until install process is done then switching to git mode.
2. Added D8 pantheon site, dev instance, using Kalabox UI. Completes and website is loadable in browser.
3. Select "Pull" on app and select dev db and files. When the app UI in Kalabox says "Pulling files." it sits for several minutes and I believe Docker crashes (see screenshots below).
4. While VM was started and fine before pull UI action for the app being added to Kalabox I checked after freeze with command `.kalabox\bin\docker-machine start Kalabox2' results in the following error output:

```
C:\Users\Matthew Giacomazzo\.kalabox\bin>docker-machine start Kalabox2
Starting "Kalabox2"...
(Kalabox2) Check network to re-create if needed...
Error setting up host only network on machine start: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm Kalabox2 --nic2 hostonly --nictype2 82540EM --nicpromisc2 deny --hostonlyadapter2 VirtualBox Host-Only Ethernet Adapter --cableconnected2 on failed:
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 493 of file VBoxManageModifyVM.cpp
```

`.kalabox\logs` Log Files: https://www.dropbox.com/sh/878ukpzqy4f6b4c/AABsQjx-S0OmhAOJscgj0dWHa?dl=0
' .docker\machine\machines\Kalabox2\Kalabox2\Logs` Log Files: https://www.dropbox.com/sh/zutyr7vbpqwn4c6/AACVMyNBpS1ULBDcvQtQtOKga?dl=0

VM before it gets stuck on "Pulling files."
![vm before](https://cloud.githubusercontent.com/assets/3443548/15123502/fa6ee59e-15d8-11e6-8466-5f47ac5a927a.png)

VM after it gets stuck on "Pulling files."
![vm after](https://cloud.githubusercontent.com/assets/3443548/15123155/25728d42-15d7-11e6-8eca-442764e2c093.png)

**Tell us more**

Tried clearing out app and re-running the Kalabox installer. No change. Seems like there are serious issues interfacing with VirtualBox and setting up Host adapters?

This is completely blocking me from using Kalabox any further.

Unfortunately my time for tinkering is up and I need to start production on another local environment to not fall behind at work at this point. If you require further information for debugging please be specific and include step by step instructions knowing I am a designer/front-end developer with little command line experience and almost no server ops experience. But that is your target audience for this product, right? :)

**Comment by Soundvessel** [comment]
Could it be related to the NAT issues fixed in VirtualBox 5.0.20. Unfortunately Kalabox doesn't work when I update and if I run the Kalabox installer again it downgrades to 5.0.16.

**Comment by pirog** [comment]
@Soundvessel its possible and im sure we will upgrade to the latest VB in the beta2. This also looks very similar to what you reported over at https://github.com/kalabox/kalabox/issues/1331

That said i can't replicate this on my Win10 Pro box following your steps :( seems to work as expected

**Comment by pirog** [comment]
@Soundvessel so i was actually able to replicate this after a few tries but im still not exactly sure why. Seems to happen inconsistently for me.
