### ISSUE TITLE
Snapshot of site missing on new PHP App

### ISSUE THREAD

**Issue by aangelinsf** [kalabox/kalabox#1601]
2.0.0 on macOS 10.11.6
fresh install

== Steps ==
1. Click "Add new site." Select D8. New site spins up.

== Results ==
A new app appears with a broken gif and "Snapshot of your site." Should be an image that says, "Click here to access your site" or similar.

== Part 2 ==
1. Click Stop.

== Results ==
Slot still shows broken gif.

Does this bug prevent you from using Kalabox?
No

**Comment by pirog** [comment]
Word. Def noticed this too. Would be a good fix for 2.0.1

**Comment by pirog** [comment]
@aangelinsf for some reason i cant replicate this anymore. Going to bump this back to 2.0.2

**Comment by reynoldsalec** [comment]
Looks like the problem here was probably around xattr attached by macOS to the image file; made an update to kalabox-app-php that should fix the problem.

**Comment by olafgrabienski** [comment]
Hey there, I'm using 2.1.1, but the problem persists:

![screen-kalabox-snapshot-missing](https://cloud.githubusercontent.com/assets/14188307/20033777/51a2f6f8-a3a9-11e6-9226-2d158d5445cc.png)

Actually, the snapshot never showed up on my machines (two Macs). I started using Kalabox with one of the releases before 2.x. Do you think, there may be an issue with file permissions on my installations? And if so, where would I find the relevant file?

**Comment by pirog** [comment]
@olafgrabienski yeah sadly it seems like something happens when we build Kalabox for production that breaks this. Going to reslot for next release.

**Comment by reynoldsalec** [comment]
@olafgrabienski FYI we found the cause of this issue (turns out we needed to tweak the way we were using grunt-contrib-copy to copy files; it was corrupting the image files in our build of Kalabox), so this should be fixed if you download 2.1.2 and build an app.

**Comment by olafgrabienski** [comment]
Everything fine, after I updated to 2.1.2 and built a new app. Thanks for fixing this!

**Comment by pirog** [comment]
Sure thing
